version: '3'
services:
  app1:
    build: ./app1
    ports:
      - "5001:5001"
    networks:
      - isolated
  # app2:
  #   build: ./app2
  #   ports:
  #     - "5002:5002"
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - app1
  #     - app2

networks:
  isolated:
    driver: overlay
    internal: true